version: "2"
services:
    agent:
        image: zabbix/zabbix-agent:alpine-3.2-latest
        privileged: true
        environment: 
            - ZBX_HOSTNAME=zabbix-monitoring
            - ZBX_SERVER_HOST=103.219.251.155
        network_mode: host

networks:
    default:
        external:
            name: "host"
